#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "cddal.y".
#

require 'racc/parser.rb'
module Opencdd
  module Cddal
    class GeneratedParser < Racc::Parser

module_eval(<<'...end cddal.y/module_eval...', 'cddal.y', 215)

def initialize(tokens)
  @tokens = tokens
  @pos = 0
end

def parse
  @tokens = @tokens.tokens if @tokens.is_a?(Opencdd::Cddal::Lexer)
  do_parse
rescue Racc::ParseError => e
  raise Opencdd::Cddal::ParseError, e.message
end

def next_token
  tok = @tokens[@pos]
  @pos += 1
  if tok.nil? || tok.kind == :EOF
    [false, false]
  else
    [tok.kind, tok.value]
  end
end

def lineno
  tok = @tokens[@pos]
  tok&.line || 0
end

def on_error(error_token_id, error_value, value_stack)
  tok = @tokens[@pos - 1]
  location = tok&.line ? " at line #{tok.line}" : ""
  token_name = token_to_str(error_token_id) || error_token_id.to_s
  raise Opencdd::Cddal::ParseError,
    "unexpected #{token_name}(#{error_value.inspect})#{location}"
end
...end cddal.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     2,   107,     8,     9,    10,    11,   106,    14,    70,    78,
    20,    60,    61,    62,    70,    71,    21,    38,    41,    81,
    82,    71,    83,    77,    13,    57,    58,    59,    63,    69,
    70,    39,    43,    22,    76,    75,    70,    73,    74,    17,
    16,    94,    95,    71,    97,    96,    24,    81,    82,    25,
    83,    77,    89,    90,   102,    91,    92,   101,   100,    89,
    90,    27,    91,    92,    49,   104,    50,   105,    17,    18,
    17,    16,    17,    16,    28,    30,    31,    36,    37,    27,
    46,    48,    30,    52,    53,    46,    55,   103,    75,   108 ]

racc_action_check = [
     1,    87,     1,     1,     1,     1,    87,     2,    70,    70,
    10,    52,    52,    52,    52,    70,    11,    32,    34,    70,
    70,    52,    70,    70,     1,    52,    52,    52,    52,    52,
    72,    32,    34,    12,    69,    69,   105,    69,    69,     8,
     8,    72,    72,   105,    72,    72,    15,   105,   105,    18,
   105,   105,    71,    71,    75,    71,    71,    75,    75,   107,
   107,    19,   107,   107,    44,    79,    44,    79,     9,     9,
    25,    25,    28,    28,    20,    21,    22,    29,    31,    33,
    37,    43,    46,    47,    48,    50,    51,    76,    77,    99 ]

racc_action_pointer = [
   nil,     0,     7,   nil,   nil,   nil,   nil,   nil,    16,    45,
   -14,    -4,    13,   nil,   nil,    37,   nil,   nil,    36,    52,
    63,    51,    71,   nil,   nil,    47,   nil,   nil,    49,    53,
   nil,    69,     7,    70,     8,   nil,   nil,    56,   nil,   nil,
   nil,   nil,   nil,    66,    54,   nil,    58,    72,    60,   nil,
    61,    62,     5,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    19,
    -1,    32,    21,   nil,   nil,    34,    63,    72,   nil,    55,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   -11,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    72,
   nil,   nil,   nil,   nil,   nil,    27,   nil,    39,   nil,   nil,
   nil ]

racc_action_default = [
    -1,   -77,   -77,    -2,    -3,    -4,    -5,    -6,   -77,   -77,
   -77,   -77,   -77,   -26,   111,    -8,   -31,   -32,   -31,   -14,
   -77,   -22,   -77,    -7,   -10,   -77,   -13,   -16,   -77,   -77,
   -25,   -77,   -77,   -14,   -77,   -21,   -23,   -77,    -9,   -11,
   -12,   -15,   -17,   -19,   -77,   -27,   -29,   -77,   -77,   -24,
   -77,   -77,   -77,   -20,   -28,   -30,   -18,   -33,   -34,   -35,
   -36,   -37,   -38,   -39,   -40,   -41,   -42,   -43,   -44,   -45,
   -77,   -77,   -77,   -47,   -48,   -77,   -77,   -69,   -59,   -77,
   -61,   -63,   -64,   -65,   -66,   -67,   -68,   -77,   -71,   -73,
   -74,   -75,   -76,   -46,   -49,   -50,   -51,   -52,   -53,   -77,
   -55,   -56,   -57,   -58,   -60,   -77,   -70,   -77,   -54,   -62,
   -72 ]

racc_goto_table = [
    88,    29,    80,    15,    19,    67,    45,    26,     1,     3,
     4,     5,     6,     7,    23,    32,    34,    42,    47,    54,
    33,    40,    56,    35,    12,    98,    51,    44,    64,    65,
    66,    68,    72,    93,    99,    79,   110,   109,    87 ]

racc_goto_check = [
    30,    15,    28,     7,     7,    22,    18,    10,     1,     2,
     3,     4,     5,     6,     8,     9,    11,    12,    13,    18,
     7,    10,    14,     7,    16,    22,    15,    17,    19,    20,
    21,    23,    24,    25,    26,    27,    30,    28,    29 ]

racc_goto_pointer = [
   nil,     8,     8,     9,    10,    11,    12,    -5,    -1,    -9,
   -12,   -11,   -17,   -25,   -30,   -20,    23,   -10,   -31,   -24,
   -23,   -22,   -47,   -21,   -37,   -39,   -41,   -35,   -68,   -33,
   -71 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    84,   nil,    86,    85,   nil,   nil,   nil,   nil,   nil,   nil,
   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 26, :_reduce_1,
  2, 26, :_reduce_2,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  3, 28, :_reduce_7,
  0, 33, :_reduce_8,
  3, 33, :_reduce_9,
  0, 34, :_reduce_10,
  2, 34, :_reduce_11,
  5, 29, :_reduce_12,
  3, 29, :_reduce_13,
  0, 35, :_reduce_14,
  3, 35, :_reduce_15,
  0, 36, :_reduce_16,
  2, 36, :_reduce_17,
  4, 37, :_reduce_18,
  0, 38, :_reduce_19,
  2, 38, :_reduce_20,
  4, 30, :_reduce_21,
  2, 31, :_reduce_22,
  4, 31, :_reduce_23,
  6, 31, :_reduce_24,
  1, 40, :_reduce_25,
  1, 41, :_reduce_26,
  1, 42, :_reduce_27,
  3, 42, :_reduce_28,
  1, 43, :_reduce_29,
  3, 43, :_reduce_30,
  1, 32, :_reduce_31,
  1, 32, :_reduce_32,
  1, 39, :_reduce_33,
  1, 39, :_reduce_34,
  1, 39, :_reduce_35,
  1, 39, :_reduce_36,
  1, 39, :_reduce_37,
  1, 39, :_reduce_38,
  1, 39, :_reduce_39,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_45,
  3, 44, :_reduce_46,
  1, 49, :_reduce_47,
  1, 49, :_reduce_48,
  1, 50, :_reduce_49,
  1, 50, :_reduce_50,
  1, 50, :_reduce_51,
  1, 50, :_reduce_52,
  1, 50, :_reduce_none,
  4, 45, :_reduce_54,
  1, 51, :_reduce_55,
  1, 51, :_reduce_56,
  1, 51, :_reduce_57,
  3, 46, :_reduce_58,
  2, 47, :_reduce_59,
  3, 47, :_reduce_60,
  1, 52, :_reduce_61,
  3, 52, :_reduce_62,
  1, 53, :_reduce_63,
  1, 53, :_reduce_64,
  1, 53, :_reduce_65,
  1, 53, :_reduce_none,
  1, 53, :_reduce_none,
  1, 53, :_reduce_none,
  1, 53, :_reduce_69,
  3, 48, :_reduce_70,
  1, 54, :_reduce_71,
  3, 54, :_reduce_72,
  1, 55, :_reduce_73,
  1, 55, :_reduce_74,
  1, 55, :_reduce_75,
  1, 55, :_reduce_76 ]

racc_reduce_n = 77

racc_shift_n = 111

racc_token_table = {
  false => 0,
  :error => 1,
  :META_CLASS => 2,
  :INSTANCE => 3,
  :ALIAS => 4,
  :IMPORT => 5,
  :TRUE => 6,
  :FALSE => 7,
  :NULL => 8,
  :LBRACE => 9,
  :RBRACE => 10,
  :COLON => 11,
  :COMMA => 12,
  :LANGLE => 13,
  :RANGLE => 14,
  :DOT => 15,
  :LPAREN => 16,
  :RPAREN => 17,
  :EQEQ => 18,
  :NEQ => 19,
  :STRING => 20,
  :NUMBER => 21,
  :DATE => 22,
  :IRDI => 23,
  :IDENT => 24 }

racc_nt_base = 25

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "META_CLASS",
  "INSTANCE",
  "ALIAS",
  "IMPORT",
  "TRUE",
  "FALSE",
  "NULL",
  "LBRACE",
  "RBRACE",
  "COLON",
  "COMMA",
  "LANGLE",
  "RANGLE",
  "DOT",
  "LPAREN",
  "RPAREN",
  "EQEQ",
  "NEQ",
  "STRING",
  "NUMBER",
  "DATE",
  "IRDI",
  "IDENT",
  "$start",
  "document",
  "declaration",
  "meta_class_decl",
  "instance_decl",
  "alias_decl",
  "import_decl",
  "ident_or_irdi",
  "opt_prop_list",
  "prop_id_list",
  "opt_assignment_block",
  "assignment_list",
  "assignment",
  "opt_language_tag",
  "value",
  "soft_as",
  "soft_from",
  "import_list",
  "import_item",
  "condition",
  "class_reference",
  "dotted_ref",
  "set",
  "tuple",
  "cond_op",
  "condition_rhs",
  "class_ref_arg",
  "set_element_list",
  "set_element",
  "tuple_element_list",
  "tuple_element" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'cddal.y', 14)
  def _reduce_1(val, _values, result)
     result = Opencdd::Cddal::AST::Document.new(declarations: [])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 15)
  def _reduce_2(val, _values, result)
     val[0].declarations << val[1]; result = val[0]
    result
  end
.,.,

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

module_eval(<<'.,.,', 'cddal.y', 27)
  def _reduce_7(val, _values, result)
     result = Opencdd::Cddal::AST::MetaClassDecl.new(irdi: val[1], property_identifiers: val[2] || [], line: lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 31)
  def _reduce_8(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 32)
  def _reduce_9(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 36)
  def _reduce_10(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 37)
  def _reduce_11(val, _values, result)
     result = val[0] + [val[1]]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 42)
  def _reduce_12(val, _values, result)
     result = Opencdd::Cddal::AST::InstanceDecl.new(
            name: val[1], meta_class_ref: val[3], assignments: val[4] || [], line: lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 45)
  def _reduce_13(val, _values, result)
     result = Opencdd::Cddal::AST::InstanceDecl.new(
            name: nil, meta_class_ref: val[1], assignments: val[2] || [], line: lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 50)
  def _reduce_14(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 51)
  def _reduce_15(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 55)
  def _reduce_16(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 56)
  def _reduce_17(val, _values, result)
     result = val[0] + [val[1]]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 61)
  def _reduce_18(val, _values, result)
     result = Opencdd::Cddal::AST::PropertyAssignment.new(
            identifier: val[0], language_tag: val[1], value: val[3], line: lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 66)
  def _reduce_19(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 67)
  def _reduce_20(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 72)
  def _reduce_21(val, _values, result)
     result = Opencdd::Cddal::AST::AliasDecl.new(alias_name: val[1], property_id: val[3], line: lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 77)
  def _reduce_22(val, _values, result)
     result = Opencdd::Cddal::AST::ImportDecl.bare(val[1], line: lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 79)
  def _reduce_23(val, _values, result)
     result = Opencdd::Cddal::AST::ImportDecl.qualified(val[1], qualifier: val[3], line: lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 81)
  def _reduce_24(val, _values, result)
     result = Opencdd::Cddal::AST::ImportDecl.selective(val[1], imported_names: val[4], line: lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 92)
  def _reduce_25(val, _values, result)
              unless val[0] == "as"
            raise Racc::ParseError, "expected 'as' keyword, got #{val[0].inspect}"
          end
          result = val[0]

    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 102)
  def _reduce_26(val, _values, result)
              unless val[0] == "from"
            raise Racc::ParseError, "expected 'from' keyword, got #{val[0].inspect}"
          end
          result = val[0]

    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 110)
  def _reduce_27(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 111)
  def _reduce_28(val, _values, result)
     result = val[0] + [val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 115)
  def _reduce_29(val, _values, result)
     result = Opencdd::Cddal::AST::ImportedName.new(name: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 116)
  def _reduce_30(val, _values, result)
     result = Opencdd::Cddal::AST::ImportedName.new(name: val[0], as: val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 120)
  def _reduce_31(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 121)
  def _reduce_32(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 125)
  def _reduce_33(val, _values, result)
     result = Opencdd::Cddal::AST::Literal.new(kind: :string, raw: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 126)
  def _reduce_34(val, _values, result)
     result = Opencdd::Cddal::AST::Literal.new(kind: :number, raw: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 127)
  def _reduce_35(val, _values, result)
     result = Opencdd::Cddal::AST::Literal.new(kind: :date, raw: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 128)
  def _reduce_36(val, _values, result)
     result = Opencdd::Cddal::AST::Literal.new(kind: :boolean, raw: "true")
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 129)
  def _reduce_37(val, _values, result)
     result = Opencdd::Cddal::AST::Literal.new(kind: :boolean, raw: "false")
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 130)
  def _reduce_38(val, _values, result)
     result = Opencdd::Cddal::AST::Literal.new(kind: :null, raw: "null")
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 131)
  def _reduce_39(val, _values, result)
     result = Opencdd::Cddal::AST::IdentifierRef.new(name: val[0])
    result
  end
.,.,

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

module_eval(<<'.,.,', 'cddal.y', 137)
  def _reduce_45(val, _values, result)
     result = Opencdd::Cddal::AST::IdentifierRef.new(name: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 142)
  def _reduce_46(val, _values, result)
     result = Opencdd::Cddal::AST::Condition.new(left: val[0], operator: val[1], right: val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 146)
  def _reduce_47(val, _values, result)
     result = "=="
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 147)
  def _reduce_48(val, _values, result)
     result = "!="
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 151)
  def _reduce_49(val, _values, result)
     result = Opencdd::Cddal::AST::Literal.new(kind: :string, raw: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 152)
  def _reduce_50(val, _values, result)
     result = Opencdd::Cddal::AST::Literal.new(kind: :number, raw: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 153)
  def _reduce_51(val, _values, result)
     result = Opencdd::Cddal::AST::IdentifierRef.new(name: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 154)
  def _reduce_52(val, _values, result)
     result = Opencdd::Cddal::AST::IdentifierRef.new(name: val[0])
    result
  end
.,.,

# reduce 53 omitted

module_eval(<<'.,.,', 'cddal.y', 160)
  def _reduce_54(val, _values, result)
     result = Opencdd::Cddal::AST::ClassReference.new(type_name: val[0], argument: val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 164)
  def _reduce_55(val, _values, result)
     result = Opencdd::Cddal::AST::IdentifierRef.new(name: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 165)
  def _reduce_56(val, _values, result)
     result = Opencdd::Cddal::AST::IdentifierRef.new(name: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 166)
  def _reduce_57(val, _values, result)
     result = Opencdd::Cddal::AST::Literal.new(kind: :string, raw: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 171)
  def _reduce_58(val, _values, result)
     result = Opencdd::Cddal::AST::IdentifierRef.new(name: val[2], owner: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 175)
  def _reduce_59(val, _values, result)
     result = Opencdd::Cddal::AST::Set.new(elements: [])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 176)
  def _reduce_60(val, _values, result)
     result = Opencdd::Cddal::AST::Set.new(elements: val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 180)
  def _reduce_61(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 181)
  def _reduce_62(val, _values, result)
     result = val[0] + [val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 185)
  def _reduce_63(val, _values, result)
     result = Opencdd::Cddal::AST::Literal.new(kind: :string, raw: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 186)
  def _reduce_64(val, _values, result)
     result = Opencdd::Cddal::AST::Literal.new(kind: :number, raw: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 187)
  def _reduce_65(val, _values, result)
     result = Opencdd::Cddal::AST::IdentifierRef.new(name: val[0])
    result
  end
.,.,

# reduce 66 omitted

# reduce 67 omitted

# reduce 68 omitted

module_eval(<<'.,.,', 'cddal.y', 191)
  def _reduce_69(val, _values, result)
     result = Opencdd::Cddal::AST::IdentifierRef.new(name: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 196)
  def _reduce_70(val, _values, result)
     result = Opencdd::Cddal::AST::Tuple.new(elements: val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 200)
  def _reduce_71(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 201)
  def _reduce_72(val, _values, result)
     result = val[0] + [val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 205)
  def _reduce_73(val, _values, result)
     result = Opencdd::Cddal::AST::Literal.new(kind: :string, raw: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 206)
  def _reduce_74(val, _values, result)
     result = Opencdd::Cddal::AST::Literal.new(kind: :number, raw: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 207)
  def _reduce_75(val, _values, result)
     result = Opencdd::Cddal::AST::IdentifierRef.new(name: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 208)
  def _reduce_76(val, _values, result)
     result = Opencdd::Cddal::AST::IdentifierRef.new(name: val[0])
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

    end   # class GeneratedParser
  end   # module Cddal
end   # module Opencdd
