# frozen_string_literal: true

require "spec_helper"

RSpec.describe Opencdd::Cddal::Serializer do
  let(:example_path) { REFERENCE_DOCS.join("examples/oceanrunner.cddal") }
  let(:database) { Opencdd::Cddal.parse_file(example_path) }
  let(:serializer) { described_class.new(database) }

  describe "#emit_entity" do
    subject(:text) { serializer.emit_entity(entity) }

    context "with a class entity" do
      let(:entity) { database.classes.first }

      it { is_expected.to start_with("# Generated by Opencdd::Cddal::Serializer") }
      it { is_expected.to include("instance ") }
      it { is_expected.to include("< MDC_C002") }
      it { is_expected.to match(/preferred_name\.(?:en)?: /) }

      it "round-trips through Opencdd::Cddal.parse" do
        reparsed = Opencdd::Cddal.parse(text)
        expect(reparsed.classes.size).to eq(1)
        round_tripped = reparsed.classes.first
        expect(round_tripped.irdi).to eq(entity.irdi)
        expect(round_tripped.preferred_name).to eq(entity.preferred_name)
      end
    end

    context "with a property entity" do
      let(:entity) { database.properties.first }

      it "emits the property meta-class" do
        expect(text).to include("< MDC_C003")
      end

      it "round-trips through Opencdd::Cddal.parse" do
        reparsed = Opencdd::Cddal.parse(text)
        expect(reparsed.properties.size).to eq(1)
        expect(reparsed.properties.first.irdi).to eq(entity.irdi)
      end
    end

    context "with a value_list entity" do
      let(:entity) { database.value_lists.first }

      it "emits the value_list meta-class" do
        expect(text).to include("< MDC_C005")
      end

      it "round-trips through Opencdd::Cddal.parse" do
        reparsed = Opencdd::Cddal.parse(text)
        expect(reparsed.value_lists.size).to eq(1)
        expect(reparsed.value_lists.first.irdi).to eq(entity.irdi)
      end
    end

    context "with nil values in raw_properties" do
      let(:entity) { database.classes.first }

      it "omits nil/empty entries rather than emitting empty rhs" do
        # All entities in the fixture have some nil keys; the emit
        # must skip them silently.
        expect(text).not_to match(/:\s*\n/)
      end
    end
  end

  describe "consistency with #to_cddal" do
    it "the entity's emitted block appears verbatim in the database emit" do
      entity = database.classes.first
      entity_text = serializer.emit_entity(entity)
      full_text = serializer.to_cddal
      # The body of emit_entity (minus header) should be a substring
      # of the full database emit.
      body = entity_text.split("\n", 2).last
      expect(full_text).to include(body.chomp)
    end
  end
end
