#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "cddal.y".
#

require 'racc/parser.rb'

require "cdd/cddal/ast"

module Cdd
  module Cddal
    class GeneratedParser < Racc::Parser

module_eval(<<'...end cddal.y/module_eval...', 'cddal.y', 177)

def initialize(tokens)
  @tokens = tokens
  @pos = 0
end

def parse
  @tokens = @tokens.tokens if @tokens.is_a?(Cdd::Cddal::Lexer)
  do_parse
rescue Racc::ParseError => e
  raise Cdd::Cddal::ParseError, e.message
end

def next_token
  tok = @tokens[@pos]
  @pos += 1
  if tok.nil? || tok.kind == :EOF
    [false, false]
  else
    [tok.kind, tok.value]
  end
end

def lineno
  tok = @tokens[@pos]
  tok&.line || 0
end

def on_error(error_token_id, error_value, value_stack)
  tok = @tokens[@pos - 1]
  location = tok&.line ? " at line #{tok.line}" : ""
  token_name = token_to_str(error_token_id) || error_token_id.to_s
  raise Cdd::Cddal::ParseError,
    "unexpected #{token_name}(#{error_value.inspect})#{location}"
end
...end cddal.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    44,    45,    46,    54,    91,    15,    14,    30,    33,    90,
    55,    12,    54,    62,    41,    42,    43,    47,    53,    55,
    54,    31,    35,    65,    66,    18,    67,    61,    88,    54,
    89,    78,    79,    19,    81,    80,    55,    15,    16,    21,
    65,    66,    22,    67,    61,     2,    24,     8,     9,    10,
    11,    60,    59,    25,    57,    58,    73,    74,    86,    75,
    76,    85,    84,    73,    74,    24,    75,    76,    15,    14,
    15,    14,    37,    38,    39,    87,    59,    92 ]

racc_action_check = [
    38,    38,    38,    38,    71,     8,     8,    26,    28,    71,
    38,     2,    54,    54,    38,    38,    38,    38,    38,    54,
    56,    26,    28,    54,    54,    10,    54,    54,    63,    89,
    63,    56,    56,    11,    56,    56,    89,     9,     9,    13,
    89,    89,    16,    89,    89,     1,    17,     1,     1,     1,
     1,    53,    53,    18,    53,    53,    55,    55,    59,    55,
    55,    59,    59,    91,    91,    27,    91,    91,    22,    22,
    25,    25,    35,    36,    37,    60,    61,    83 ]

racc_action_pointer = [
   nil,    45,    11,   nil,   nil,   nil,   nil,   nil,   -18,    14,
     1,    13,   nil,    30,   nil,   nil,    29,    37,    42,   nil,
   nil,   nil,    45,   nil,   nil,    47,    -3,    56,    -2,   nil,
   nil,   nil,   nil,   nil,   nil,    57,    62,    50,    -6,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    36,     3,    36,    11,   nil,   nil,    38,
    51,    60,   nil,    18,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    -8,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    60,   nil,   nil,   nil,   nil,   nil,    20,
   nil,    43,   nil,   nil,   nil ]

racc_action_default = [
    -1,   -69,   -69,    -2,    -3,    -4,    -5,    -6,   -69,   -69,
   -69,   -69,    95,    -8,   -23,   -24,   -23,   -14,   -69,   -22,
    -7,   -10,   -69,   -13,   -16,   -69,   -69,   -14,   -69,   -21,
    -9,   -11,   -12,   -15,   -17,   -19,   -69,   -69,   -69,   -20,
   -18,   -25,   -26,   -27,   -28,   -29,   -30,   -31,   -32,   -33,
   -34,   -35,   -36,   -37,   -69,   -69,   -69,   -39,   -40,   -69,
   -69,   -61,   -51,   -69,   -53,   -55,   -56,   -57,   -58,   -59,
   -60,   -69,   -63,   -65,   -66,   -67,   -68,   -38,   -41,   -42,
   -43,   -44,   -45,   -69,   -47,   -48,   -49,   -50,   -52,   -69,
   -62,   -69,   -46,   -54,   -64 ]

racc_goto_table = [
    72,    51,    64,    13,    17,    23,     1,     3,     4,     5,
     6,     7,    20,    26,    28,    32,    34,    27,    36,    82,
    29,    40,    48,    49,    50,    52,    56,    77,    83,    63,
    71,   nil,   nil,   nil,   nil,   nil,    94,    93 ]

racc_goto_check = [
    26,    18,    24,     7,     7,    10,     1,     2,     3,     4,
     5,     6,     8,     9,    11,    10,    12,     7,    13,    18,
     7,    14,    15,    16,    17,    19,    20,    21,    22,    23,
    25,   nil,   nil,   nil,   nil,   nil,    26,    24 ]

racc_goto_pointer = [
   nil,     6,     6,     7,     8,     9,    10,    -5,    -1,    -8,
   -12,   -10,   -12,   -17,   -17,   -16,   -15,   -14,   -37,   -13,
   -27,   -29,   -31,   -25,   -52,   -25,   -55 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    68,   nil,    70,    69,
   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 26, :_reduce_1,
  2, 26, :_reduce_2,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  3, 28, :_reduce_7,
  0, 33, :_reduce_8,
  3, 33, :_reduce_9,
  0, 34, :_reduce_10,
  2, 34, :_reduce_11,
  5, 29, :_reduce_12,
  3, 29, :_reduce_13,
  0, 35, :_reduce_14,
  3, 35, :_reduce_15,
  0, 36, :_reduce_16,
  2, 36, :_reduce_17,
  4, 37, :_reduce_18,
  0, 38, :_reduce_19,
  2, 38, :_reduce_20,
  4, 30, :_reduce_21,
  2, 31, :_reduce_22,
  1, 32, :_reduce_23,
  1, 32, :_reduce_24,
  1, 39, :_reduce_25,
  1, 39, :_reduce_26,
  1, 39, :_reduce_27,
  1, 39, :_reduce_28,
  1, 39, :_reduce_29,
  1, 39, :_reduce_30,
  1, 39, :_reduce_31,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_37,
  3, 40, :_reduce_38,
  1, 45, :_reduce_39,
  1, 45, :_reduce_40,
  1, 46, :_reduce_41,
  1, 46, :_reduce_42,
  1, 46, :_reduce_43,
  1, 46, :_reduce_44,
  1, 46, :_reduce_none,
  4, 41, :_reduce_46,
  1, 47, :_reduce_47,
  1, 47, :_reduce_48,
  1, 47, :_reduce_49,
  3, 42, :_reduce_50,
  2, 43, :_reduce_51,
  3, 43, :_reduce_52,
  1, 48, :_reduce_53,
  3, 48, :_reduce_54,
  1, 49, :_reduce_55,
  1, 49, :_reduce_56,
  1, 49, :_reduce_57,
  1, 49, :_reduce_none,
  1, 49, :_reduce_none,
  1, 49, :_reduce_none,
  1, 49, :_reduce_61,
  3, 44, :_reduce_62,
  1, 50, :_reduce_63,
  3, 50, :_reduce_64,
  1, 51, :_reduce_65,
  1, 51, :_reduce_66,
  1, 51, :_reduce_67,
  1, 51, :_reduce_68 ]

racc_reduce_n = 69

racc_shift_n = 95

racc_token_table = {
  false => 0,
  :error => 1,
  :META_CLASS => 2,
  :INSTANCE => 3,
  :ALIAS => 4,
  :IMPORT => 5,
  :TRUE => 6,
  :FALSE => 7,
  :NULL => 8,
  :LBRACE => 9,
  :RBRACE => 10,
  :COLON => 11,
  :COMMA => 12,
  :LANGLE => 13,
  :RANGLE => 14,
  :DOT => 15,
  :LPAREN => 16,
  :RPAREN => 17,
  :EQEQ => 18,
  :NEQ => 19,
  :STRING => 20,
  :NUMBER => 21,
  :DATE => 22,
  :IRDI => 23,
  :IDENT => 24 }

racc_nt_base = 25

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "META_CLASS",
  "INSTANCE",
  "ALIAS",
  "IMPORT",
  "TRUE",
  "FALSE",
  "NULL",
  "LBRACE",
  "RBRACE",
  "COLON",
  "COMMA",
  "LANGLE",
  "RANGLE",
  "DOT",
  "LPAREN",
  "RPAREN",
  "EQEQ",
  "NEQ",
  "STRING",
  "NUMBER",
  "DATE",
  "IRDI",
  "IDENT",
  "$start",
  "document",
  "declaration",
  "meta_class_decl",
  "instance_decl",
  "alias_decl",
  "import_decl",
  "ident_or_irdi",
  "opt_prop_list",
  "prop_id_list",
  "opt_assignment_block",
  "assignment_list",
  "assignment",
  "opt_language_tag",
  "value",
  "condition",
  "class_reference",
  "dotted_ref",
  "set",
  "tuple",
  "cond_op",
  "condition_rhs",
  "class_ref_arg",
  "set_element_list",
  "set_element",
  "tuple_element_list",
  "tuple_element" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'cddal.y', 12)
  def _reduce_1(val, _values, result)
     result = Cdd::Cddal::AST::Document.new(declarations: [])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 13)
  def _reduce_2(val, _values, result)
     val[0].declarations << val[1]; result = val[0]
    result
  end
.,.,

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

module_eval(<<'.,.,', 'cddal.y', 25)
  def _reduce_7(val, _values, result)
     result = Cdd::Cddal::AST::MetaClassDecl.new(irdi: val[1], property_identifiers: val[2] || [], line: lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 29)
  def _reduce_8(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 30)
  def _reduce_9(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 34)
  def _reduce_10(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 35)
  def _reduce_11(val, _values, result)
     result = val[0] + [val[1]]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 40)
  def _reduce_12(val, _values, result)
     result = Cdd::Cddal::AST::InstanceDecl.new(
            name: val[1], meta_class_ref: val[3], assignments: val[4] || [], line: lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 43)
  def _reduce_13(val, _values, result)
     result = Cdd::Cddal::AST::InstanceDecl.new(
            name: nil, meta_class_ref: val[1], assignments: val[2] || [], line: lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 48)
  def _reduce_14(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 49)
  def _reduce_15(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 53)
  def _reduce_16(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 54)
  def _reduce_17(val, _values, result)
     result = val[0] + [val[1]]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 59)
  def _reduce_18(val, _values, result)
     result = Cdd::Cddal::AST::PropertyAssignment.new(
            identifier: val[0], language_tag: val[1], value: val[3], line: lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 64)
  def _reduce_19(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 65)
  def _reduce_20(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 70)
  def _reduce_21(val, _values, result)
     result = Cdd::Cddal::AST::AliasDecl.new(alias_name: val[1], property_id: val[3], line: lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 75)
  def _reduce_22(val, _values, result)
     result = Cdd::Cddal::AST::ImportDecl.new(url: val[1], line: lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 79)
  def _reduce_23(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 80)
  def _reduce_24(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 84)
  def _reduce_25(val, _values, result)
     result = Cdd::Cddal::AST::Literal.new(kind: :string, raw: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 85)
  def _reduce_26(val, _values, result)
     result = Cdd::Cddal::AST::Literal.new(kind: :number, raw: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 86)
  def _reduce_27(val, _values, result)
     result = Cdd::Cddal::AST::Literal.new(kind: :date, raw: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 87)
  def _reduce_28(val, _values, result)
     result = Cdd::Cddal::AST::Literal.new(kind: :boolean, raw: "true")
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 88)
  def _reduce_29(val, _values, result)
     result = Cdd::Cddal::AST::Literal.new(kind: :boolean, raw: "false")
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 89)
  def _reduce_30(val, _values, result)
     result = Cdd::Cddal::AST::Literal.new(kind: :null, raw: "null")
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 90)
  def _reduce_31(val, _values, result)
     result = Cdd::Cddal::AST::IdentifierRef.new(name: val[0])
    result
  end
.,.,

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

module_eval(<<'.,.,', 'cddal.y', 96)
  def _reduce_37(val, _values, result)
     result = Cdd::Cddal::AST::IdentifierRef.new(name: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 101)
  def _reduce_38(val, _values, result)
     result = Cdd::Cddal::AST::Condition.new(left: val[0], operator: val[1], right: val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 105)
  def _reduce_39(val, _values, result)
     result = "=="
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 106)
  def _reduce_40(val, _values, result)
     result = "!="
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 110)
  def _reduce_41(val, _values, result)
     result = Cdd::Cddal::AST::Literal.new(kind: :string, raw: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 111)
  def _reduce_42(val, _values, result)
     result = Cdd::Cddal::AST::Literal.new(kind: :number, raw: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 112)
  def _reduce_43(val, _values, result)
     result = Cdd::Cddal::AST::IdentifierRef.new(name: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 113)
  def _reduce_44(val, _values, result)
     result = Cdd::Cddal::AST::IdentifierRef.new(name: val[0])
    result
  end
.,.,

# reduce 45 omitted

module_eval(<<'.,.,', 'cddal.y', 119)
  def _reduce_46(val, _values, result)
     result = Cdd::Cddal::AST::ClassReference.new(type_name: val[0], argument: val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 123)
  def _reduce_47(val, _values, result)
     result = Cdd::Cddal::AST::IdentifierRef.new(name: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 124)
  def _reduce_48(val, _values, result)
     result = Cdd::Cddal::AST::IdentifierRef.new(name: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 125)
  def _reduce_49(val, _values, result)
     result = Cdd::Cddal::AST::Literal.new(kind: :string, raw: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 130)
  def _reduce_50(val, _values, result)
     result = Cdd::Cddal::AST::IdentifierRef.new(name: val[2], owner: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 134)
  def _reduce_51(val, _values, result)
     result = Cdd::Cddal::AST::Set.new(elements: [])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 135)
  def _reduce_52(val, _values, result)
     result = Cdd::Cddal::AST::Set.new(elements: val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 139)
  def _reduce_53(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 140)
  def _reduce_54(val, _values, result)
     result = val[0] + [val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 144)
  def _reduce_55(val, _values, result)
     result = Cdd::Cddal::AST::Literal.new(kind: :string, raw: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 145)
  def _reduce_56(val, _values, result)
     result = Cdd::Cddal::AST::Literal.new(kind: :number, raw: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 146)
  def _reduce_57(val, _values, result)
     result = Cdd::Cddal::AST::IdentifierRef.new(name: val[0])
    result
  end
.,.,

# reduce 58 omitted

# reduce 59 omitted

# reduce 60 omitted

module_eval(<<'.,.,', 'cddal.y', 150)
  def _reduce_61(val, _values, result)
     result = Cdd::Cddal::AST::IdentifierRef.new(name: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 155)
  def _reduce_62(val, _values, result)
     result = Cdd::Cddal::AST::Tuple.new(elements: val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 159)
  def _reduce_63(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 160)
  def _reduce_64(val, _values, result)
     result = val[0] + [val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 164)
  def _reduce_65(val, _values, result)
     result = Cdd::Cddal::AST::Literal.new(kind: :string, raw: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 165)
  def _reduce_66(val, _values, result)
     result = Cdd::Cddal::AST::Literal.new(kind: :number, raw: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 166)
  def _reduce_67(val, _values, result)
     result = Cdd::Cddal::AST::IdentifierRef.new(name: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cddal.y', 167)
  def _reduce_68(val, _values, result)
     result = Cdd::Cddal::AST::IdentifierRef.new(name: val[0])
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

    end   # class GeneratedParser
  end   # module Cddal
end   # module Cdd
