# frozen_string_literal: true

module Cdd
  module Cddal
    class Serializer
      # Matches exactly the values the CDDAL lexer can tokenize as a
      # single non-string token: keywords, numbers, dates, IRDIs,
      # local refs, and bare identifiers. Anything not matching must
      # be emitted as a quoted string literal so the lexer can reparse
      # it via scan_string_literal (which is UTF-8 aware via getch).
      UNQUOTED_VALUE_RE = /\A(?:
        true|false|null|
        -?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?|
        \d{4}-\d{2}-\d{2}|
        [0-9]+\/[0-9]+\/\/\/[A-Za-z0-9_]+(?:_[0-9]+)?\#[A-Za-z0-9_]+|
        [A-Za-z_][A-Za-z0-9_]*\#[A-Za-z0-9_]+(?:\#\#[A-Za-z0-9_]+)?|
        [A-Za-z_][A-Za-z0-9_]*
      )\z/x.freeze

      HEADER = <<~CDDAL
        # Generated by Cdd::Cddal::Serializer
      CDDAL

      attr_reader :database

      def initialize(database)
        @database = database
      end

      def to_cddal
        lines = [HEADER.chomp]
        emit_default_aliases(lines)
        emit_value_lists(lines)
        emit_value_terms(lines)
        emit_units(lines)
        emit_class_tree(lines)
        emit_rooted_properties(lines)
        emit_relations(lines)
        emit_view_controls(lines)
        lines.join("\n") + "\n"
      end

      private

      def emit_default_aliases(lines)
        lines << ""
        Cdd::PropertyIds::REGISTRY.each_value do |entry|
          entry.aliases.each do |alias_name|
            lines << "alias #{alias_name}: #{entry.id}"
          end
        end
      end

      def emit_value_lists(lines)
        lists = @database.value_lists.sort_by { |vl| vl.code.to_s }
        return if lists.empty?
        lines << ""
        lists.each do |vl|
          lines.concat(emit_instance(vl))
        end
      end

      def emit_value_terms(lines)
        terms = @database.value_terms.sort_by { |vt| vt.code.to_s }
        return if terms.empty?
        lines << ""
        terms.each do |vt|
          lines.concat(emit_instance(vt))
        end
      end

      def emit_units(lines)
        units = @database.units.sort_by { |u| u.code.to_s }
        return if units.empty?
        lines << ""
        units.each do |u|
          lines.concat(emit_instance(u))
        end
      end

      def emit_class_tree(lines)
        roots = @database.root_classes.sort_by { |k| k.code.to_s }
        return if roots.empty?
        lines << ""
        roots.each do |root|
          walk_class(root, lines, 0)
        end
      end

      def walk_class(klass, lines, depth)
        lines.concat(emit_instance(klass))
        sorted_children = klass.children.sort_by { |c| c.code.to_s }
        sorted_children.each { |c| walk_class(c, lines, depth + 1) }
      end

      def emit_rooted_properties(lines)
        emitted = Set.new
        @database.classes.sort_by { |k| k.code.to_s }.each do |klass|
          props = @database.properties_of(klass).sort_by { |p| p.code.to_s }
          props.each do |prop|
            next if emitted.include?(prop.irdi)
            emitted << prop.irdi
            lines.concat(emit_instance(prop))
          end
        end
        unrooted = @database.properties.reject { |p| emitted.include?(p.irdi) }.sort_by { |p| p.code.to_s }
        unrooted.each { |p| lines.concat(emit_instance(p)) }
      end

      def emit_relations(lines)
        rels = @database.relations.sort_by { |r| r.code.to_s }
        return if rels.empty?
        lines << ""
        rels.each { |r| lines.concat(emit_instance(r)) }
      end

      def emit_view_controls(lines)
        vcs = @database.view_controls.sort_by { |v| v.code.to_s }
        return if vcs.empty?
        lines << ""
        vcs.each { |v| lines.concat(emit_instance(v)) }
      end

      def emit_instance(entity)
        name = symbol_name_for(entity)
        meta = meta_class_for(entity)
        out = []
        out << ""
        out << "instance #{name} < #{meta} {"
        emit_properties(entity).each { |line| out << "  #{line}" }
        out << "}"
        out
      end

      def emit_properties(entity)
        out = []
        entity.properties.each do |key, value|
          next if value.nil? || value.to_s.empty?
          name = key.to_s
          base = name.sub(/\.\w+\z/, "")
          lang_match = name.match(/\.(?<lang>[a-zA-Z]{2,3}(?:-[A-Za-z0-9]+)?)\z/)
          lang = lang_match && lang_match[:lang]
          alias_name = alias_for_property_id(base)
          display_key = lang ? "#{alias_name}.#{lang}" : alias_name
          rhs = format_value(value)
          out << "#{display_key}: #{rhs}"
        end
        out
      end

      def alias_for_property_id(property_id)
        name = property_id.to_s
        base = name.sub(/\.\w+\z/, "")
        Cdd::PropertyIds.entry(base)&.aliases&.first || name
      end

      def language_suffix(property_id)
        m = property_id.to_s.match(/\.(?<lang>[a-zA-Z]{2,3}(-[A-Za-z0-9]+)?)\z/)
        m && m[:lang]
      end

      def format_value(value)
        s = value.to_s
        return quote_string(s) if string_literal?(s)
        return format_set(s) if set_like?(s)
        s
      end

      def string_literal?(s)
        !s.match?(UNQUOTED_VALUE_RE)
      end

      def quote_string(s)
        escaped = s
          .gsub("\\") { "\\\\" }
          .gsub('"')  { "\\\"" }
          .gsub("\n") { "\\n" }
          .gsub("\r") { "\\r" }
          .gsub("\t") { "\\t" }
          .gsub("\b") { "\\b" }
          .gsub("\f") { "\\f" }
        "\"#{escaped}\""
      end

      def set_like?(s)
        s.start_with?("(") && s.end_with?(")")
      end

      def format_set(s)
        elements = s[1..-2].split(",").map(&:strip).reject(&:empty?)
        "{ #{elements.join(', ')} }"
      end

      def symbol_name_for(entity)
        code = entity.code&.to_s
        return code if code && !code.empty?
        preferred = entity.preferred_name&.to_s
        return "instance" unless preferred
        safe = preferred.gsub(/[^A-Za-z0-9_]/, "_").gsub(/\A(\d)/, "_\\1")
        safe.empty? ? "instance" : safe
      end

      def meta_class_for(entity)
        type = entity.type
        code = Cdd::MetaClasses.meta_class_for_type(type) if type
        code || entity.meta_class_irdi&.code || Cdd::MetaClasses::MDC_C002
      end
    end
  end
end
